### ISSUE TITLE
Textbox expands beyond the webpage issue

### ISSUE THREAD

**Issue by Immutablevoid** [jatinAroraGit/note-down#1]
The textbox expands if there are 7 or more lines of text:
![note down](https://user-images.githubusercontent.com/30512065/65158436-55738500-da00-11e9-80fe-bb736567c0a9.png)`

May cause problems in the future if more content is added below the textbox.  
**Solution**: Add a scrollbar to the textbox, so the textbox does not expand

I would like to work on this issue.

Best Regards,
Paul Luu

**Comment by jatinAroraGit** [comment]
Hey @ImmutableBox ,
You can go ahead and add this.
Thanks.

**Comment by jatinAroraGit** [comment]
This issue was resolved by @ImmutableBox  in the commit https://github.com/jatinAroraGit/note-down/commit/c1e121346df2ac2efcb1aff3bc7588b7aa2de432
