### ISSUE TITLE
Notepad should have focus when page loads

### ISSUE THREAD

**Issue by humphd** [jatinAroraGit/note-down#3]
I was testing out your project, and it looks great.  One thing I notice is that the notepad area doesn't have focus when I load the page, and I have to click to start typing.  It might be nice to have it get focus on load.

I'll try to fix this for you.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
Sure go ahead.

**Comment by jatinAroraGit** [comment]
This issue was fixed in commit https://github.com/jatinAroraGit/note-down/commit/f7eabf3c7f345311e4b37c24f256659570f1e20a
